# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: cargo
    directory: "/"
    schedule:
      interval: "weekly"
    assignees:
      - "ADD-SP"
    commit-message:
      prefix: "chore(Cargo.toml)"

  - package-ecosystem: cargo
    directory: "/fuzz"
    schedule:
      interval: "weekly"
    assignees:
      - "ADD-SP"
    commit-message:
      prefix: "chore(fuzz/Cargo.toml)"

  - package-ecosystem: "github-actions"
    # Workflow files stored in the default location of `.github/workflows`. (You don't need to specify `/.github/workflows` for `directory`. You can use `directory: "/"`.)
    directory: "/"
    schedule:
      interval: "weekly"
    assignees:
      - "ADD-SP"
    commit-message:
      prefix: "chore(.github/workflows)"
